# Generated by Django 3.2.8 on 2021-12-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourrecipe',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='favourrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
    ]
