# Generated by Django 3.2.9 on 2021-12-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20211208_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bascket',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
