# Generated by Django 3.2.8 on 2022-02-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_alter_component_recipe'),
        ('logic', '0003_rename_recipes_bascket_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_recipes', to='recipes.recipe', verbose_name='Рецепты в списке покупок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL, verbose_name='Корзина покупок')),
            ],
            options={
                'verbose_name': 'Список рецептов для покупки',
                'verbose_name_plural': 'Списки рецептов для покупки',
                'ordering': ('user',),
            },
        ),
        migrations.DeleteModel(
            name='Bascket',
        ),
    ]
