# Generated by Django 3.2.8 on 2021-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(upload_to='recipes/', verbose_name='Картинка готового блюда'),
        ),
    ]
